### model
model_name_or_path: ./models/gemma-2b
quantization_bit: 4
quantization_method: bnb  
trust_remote_code: false  
upcast_layernorm: true               

### method
stage: sft  
do_train: true
finetuning_type: lora 
lora_rank: 64 
lora_target: all  

### dataset
dataset: alpaca_en_demo  
template: gemma  
cutoff_len: 256  
max_samples: 1000 
overwrite_cache: true
preprocessing_num_workers: 8  

### output
output_dir: saves/gemma-2b/lora/sft 
logging_steps: 10  
save_steps: 500 
plot_loss: true  
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard 

### train
per_device_train_batch_size: 1  
gradient_accumulation_steps: 8  
learning_rate: 1.0e-4  
num_train_epochs: 3.0  
lr_scheduler_type: cosine  
warmup_ratio: 0.1  
bf16: false  
fp16: true  
optim: paged_adamw_8bit  
ddp_timeout: 180000000  
gradient_checkpointing: true 
gradient_checkpointing_kwargs:
  use_reentrant: false  
dataloader_num_workers: 0  

### eval
val_size: 0.1  
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500